# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Matthieu Méchineau | PORTFOLIO
# Description of the Site
description: Une vitrine vers tous mes travaux créatifs
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Matthieu Méchineau, Portfolio, Dev, Video Games, Poetry
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: matthieu.mechineau@outlook.com
facebook_username: matthieu.mechineau
twitter_username: 
instagram_username: /
linkedin_username: matthieu-méchineau-58904227b
github_username:  MMeche
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
telephone_number: "+33 6 52 09 73 30"
discord_id : "402833659343929344"
itch_username : mmeche

# Google Analytics
google-analytics: G-8ECH6X3PGT

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Matthieu Méchineau
# URL for the Image of the Author
author-image: assets/images/me_reducted.jpg #https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: "Bonjour, moi c'est Matthieu, ingénieur créatif. Qu'est-ce qu'un ingénieur créatif me direz-vous... Fort de ma formation à la fois en sciences et en arts, je sais diriger et opérer au sein d'équipes au profils variés tels que des développeurs de logiciel, des graphistes, des techniciens ou des artistes pour la réalisation de projets innovants. En dernière année d'un diplôme d'ingénieur Image Multimédia Audiovisuel Communication (IMAC) à l'ESIEE et entamant actuellement une maîtrise en création numérique à l'Université du Québec en Abitibi-Temiscamingue (UQAT), mes compétences dans le domaine numérique sont larges et diversifiées. Passionné depuis toujours par le jeu vidéo, je les mets principalement au service de la création d'expériences vidéoludiques inédites et engageantes.\n\n
Cependant je suis apte à travailler avec l'image sous toute ses formes que ce soit par la programmation 3D (API OpenGL, moteurs de jeu Unity, UnrealEngine , Godot), les arts numériques (Modelling, texturing, animation sous Blender, motion design, outils VR), ou l'audiovisuel (création de fiction, captation image et son, post-production). C'est ainsi fort de ma polyvalence que je suis en recherche active d'un stage d'une durée de 6 mois pouvant commencer dès mai 2025.\n\n

Vous trouverez sur ce site, certaines de mes réalisations, achevées ou en cours de finition, ainsi que la trace de mon activité artistique personnelle incarnée dans mes poèmes."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/mmeche

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
